import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

/// Application localizations
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = [
    Locale('en', ''),
    Locale('ur', ''),
  ];

  // Load translations from .arb files
  static Map<String, Map<String, String>> _translations = {};

  static Future<void> loadTranslations() async {
    // English translations
    _translations['en'] = {
      'appName': 'Pharmacy POS',
      'appTagline': 'Professional Pharmacy Management',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'search': 'Search',
      'filter': 'Filter',
      'clear': 'Clear',
      'retry': 'Retry',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'close': 'Close',
      'login': 'Login',
      'logout': 'Logout',
      'email': 'Email',
      'password': 'Password',
      'forgotPassword': 'Forgot Password?',
      'register': 'Register',
      'createAccount': 'Create Account',
      'dashboard': 'Dashboard',
      'sales': 'Sales',
      'inventory': 'Inventory',
      'products': 'Products',
      'purchases': 'Purchases',
      'reports': 'Reports',
      'staff': 'Staff',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'appearance': 'Appearance',
      'darkMode': 'Dark Mode',
      'theme': 'Theme',
      'selectTheme': 'Select Theme',
      'defaultTheme': 'Default',
      'pharmacyBlue': 'Pharmacy Blue',
      'medicalGreen': 'Medical Green',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'english': 'English',
      'urdu': 'اردو (Urdu)',
      'notifications': 'Notifications',
      'lowStockAlerts': 'Low Stock Alerts',
      'expiryAlerts': 'Expiry Alerts',
      'systemNotifications': 'System Notifications',
      'about': 'About',
      'version': 'Version',
      'termsOfService': 'Terms of Service',
      'privacyPolicy': 'Privacy Policy',
      'areYouSureLogout': 'Are you sure you want to logout?',
      'editProfile': 'Edit Profile',
      'chooseFromGallery': 'Choose from Gallery',
      'takePhoto': 'Take Photo',
      'removePhoto': 'Remove Photo',
      'profileImageUpdated': 'Profile image updated',
      'profileImageRemoved': 'Profile image removed',
      'darkModeEnabled': 'Dark mode enabled',
      'lightModeEnabled': 'Light mode enabled',
      'languageChanged': 'Language changed to {language}. Changes applied instantly.',
      'themeChanged': 'Theme changed to {theme}',
      'lowStockAlertsEnabled': 'Low stock alerts enabled',
      'lowStockAlertsDisabled': 'Low stock alerts disabled',
      'expiryAlertsEnabled': 'Expiry alerts enabled',
      'expiryAlertsDisabled': 'Expiry alerts disabled',
      'systemNotificationsEnabled': 'System notifications enabled',
      'systemNotificationsDisabled': 'System notifications disabled',
      'subscriptions': 'Subscriptions',
      'categories': 'Categories',
      'inventoryDetails': 'Inventory Details',
      'adjustStock': 'Adjust Stock',
      'transferStock': 'Transfer Stock',
      'printLabel': 'Print Label',
      'addStock': 'Add Stock',
      'batch': 'Batch',
      'quantity': 'Quantity',
      'remainingQuantity': 'Remaining Quantity',
      'costPrice': 'Cost Price',
      'sellingPrice': 'Selling Price',
      'expiryDate': 'Expiry Date',
      'expired': 'Expired',
      'expiringSoon': 'Expiring Soon',
      'valid': 'Valid',
      'supplier': 'Supplier',
      'purchaseDate': 'Purchase Date',
      'location': 'Location',
      'additionalInformation': 'Additional Information',
      'lowStock': 'Low Stock',
      'newQuantity': 'New Quantity',
      'quantityToTransfer': 'Quantity to Transfer',
      'transferTo': 'Transfer To',
      'stockAdjusted': 'Stock adjusted successfully',
      'stockTransferred': 'Stock transferred successfully',
      'printingLabel': 'Printing label...',
      'deleteInventory': 'Delete Inventory',
      'deleteInventoryConfirmation': 'Are you sure you want to delete this inventory item?',
      'inventoryDeleted': 'Inventory deleted',
      'productName': 'Product Name',
      'description': 'Description',
      'barcode': 'Barcode',
      'sku': 'SKU',
      'price': 'Price',
      'category': 'Category',
      'addProduct': 'Add Product',
      'editProduct': 'Edit Product',
      'updateProduct': 'Update Product',
      'productAdded': 'Product added',
      'productUpdated': 'Product updated',
      'noProducts': 'No products found',
      'pos': 'POS',
      'cart': 'Cart',
      'subtotal': 'Subtotal',
      'discount': 'Discount',
      'tax': 'Tax',
      'total': 'Total',
      'paymentMethod': 'Payment Method',
      'processSale': 'Process Sale',
      'cartEmpty': 'Cart is empty',
      'filterByCategory': 'Filter by Category',
      'allCategories': 'All Categories',
      'searchProducts': 'Search products or scan barcode',
      'saleSummary': 'Sale Summary',
      'invoice': 'INVOICE',
      'items': 'Items',
      'printReceipt': 'Print Receipt',
      'downloadReceipt': 'Download PDF',
      'shareReceipt': 'Share',
      'receiptSent': 'Receipt sent to printer',
      'receiptDownloaded': 'Receipt downloaded',
      'receiptReady': 'Receipt ready to share',
      'thankYou': 'Thank you for your purchase!',
      'salesReport': 'Sales Report',
      'inventoryReport': 'Inventory Report',
      'generateReport': 'Generate Report',
      'exportToExcel': 'Export to Excel',
      'exportToWord': 'Export to Word',
      'exportToPdf': 'Export to PDF',
      'profile': 'Profile',
      'editProfile': 'Edit Profile',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'english': 'English',
      'urdu': 'Urdu',
      'theme': 'Theme',
      'defaultTheme': 'Default',
      'pharmacyBlue': 'Pharmacy Blue',
      'medicalGreen': 'Medical Green',
      'exitMessage': 'Press back again to exit',
      'exitApp': 'Exit App',
      'exitConfirmation': 'Are you sure you want to exit?',
      'exit': 'Exit',
      'noInventoryItems': 'No inventory items found',
      'filterInventory': 'Filter Inventory',
      'clearFilters': 'Clear Filters',
      'scanBarcode': 'Scan Barcode',
      'selectCustomer': 'Select Customer',
      'walkInCustomer': 'Walk-in Customer',
      'change': 'Change',
      'addCustomer': 'Add Customer',
      'added': 'added',
      'confirmSale': 'Confirm Sale',
      'customer': 'Customer',
      'amount': 'Amount',
      'newPurchase': 'New Purchase',
      'customers': 'Customers',
      'searchCustomers': 'Search customers...',
      'noCustomers': 'No customers found',
      'addFirstCustomer': 'Add your first customer to get started',
      'viewHistory': 'View History',
      'deleteCustomer': 'Delete Customer',
      'deleteCustomerConfirmation': 'Are you sure you want to delete',
      'customerDeleted': 'Customer deleted',
      'editCustomer': 'Edit Customer',
      'name': 'Name',
      'phone': 'Phone',
      'address': 'Address',
      'city': 'City',
      'country': 'Country',
      'dateOfBirth': 'Date of Birth',
      'gender': 'Gender',
      'customerDetails': 'Customer Details',
      'totalPurchases': 'Total Purchases',
      'totalSpent': 'Total Spent',
      'purchaseHistory': 'Purchase History',
      'noPurchaseHistory': 'No purchase history',
      'editPurchase': 'Edit Purchase',
      'supplierName': 'Supplier Name',
      'invoiceNumber': 'Invoice Number',
      'purchaseDate': 'Purchase Date',
      'addItem': 'Add Item',
      'editItem': 'Edit Item',
      'noItemsAdded': 'No items added yet',
      'totalAmount': 'Total Amount',
      'attachedFiles': 'Attached Files',
      'addImage': 'Add Image',
      'addFile': 'Add File',
      'noFilesAttached': 'No files attached',
      'createPurchase': 'Create Purchase',
      'updatePurchase': 'Update Purchase',
      'purchaseCreated': 'Purchase created successfully',
      'addAtLeastOneItem': 'Please add at least one item',
      'product': 'Product',
      'pleaseSelectProduct': 'Please select a product',
      'batchNumber': 'Batch Number',
      'selectDate': 'Select Date',
      // POS Enhanced
      'searchProductsBarcode': 'Search products, barcode, SKU, or / for customer',
      'advancedFilters': 'Advanced Filters',
      'stockOnHand': 'Stock on Hand',
      'variants': 'Variants',
      'selectVariant': 'Select Variant',
      'productType': 'Product Type',
      'otc': 'OTC',
      'rx': 'RX',
      'scriptsWaiting': 'Scripts Waiting',
      'companionProducts': 'Companion Products',
      'multiBuy': 'Multi-Buy',
      // Store/Branch Management
      'selectStore': 'Select Store',
      'switchStore': 'Switch Store',
      'stores': 'Stores',
      'newStore': 'New Store',
      'searchStores': 'Search stores...',
      'noStores': 'No stores found',
      'switchedTo': 'Switched to',
      'storeTimings': 'Store Timings',
      'addStoreTiming': 'Add Store Timing',
      'serviceType': 'Service Type',
      'day': 'Day',
      'startTime': 'Start Time',
      'endTime': 'End Time',
      'delivery': 'Delivery',
      'collection': 'Collection',
      'dineIn': 'Dine-in',
      'deliveryRates': 'Delivery Rates',
      'addDeliveryRate': 'Add Delivery Rate',
      'ratePerMileKm': 'Rate per mile/km',
      'minimumDistance': 'Minimum Distance',
      'maximumDistance': 'Maximum Distance',
      'deliveryTime': 'Delivery Time',
      'addOns': 'Add-ons',
      'addOn': 'Add On',
      'ingredients': 'Ingredients',
      'productSizes': 'Product Sizes',
      'isAddonItem': 'Is addon item?',
      'allergyNotes': 'Allergy Notes',
      'enterAllergyNotes': 'Enter allergy notes...',
      'percentageDiscount': 'Percentage Discount',
      'addPercentageDiscount': 'Add Percentage Discount (Optional)',
      'categoryNote': 'Category Note (Optional)',
      'enterCategoryNote': 'Enter category note here...',
      'sorting': 'Sorting',
      'addSortingId': 'Add Sorting ID',
      'shortDescription': 'Short Description',
      'isOpenAllDay': 'Is Open All Day',
      // Reports Metrics
      'salesAndRevenueMetrics': 'Sales and Revenue Metrics',
      'trackSalesRevenue': 'Track sales and revenue metrics with detailed insights.',
      'customerMetrics': 'Customer Metrics',
      'analyzeCustomerBehavior': 'Analyze customer behavior and engagement patterns.',
      'orderMetrics': 'Order Metrics',
      'monitorOrderTrends': 'Monitor order trends and operational efficiency.',
      'totalSales': 'Total Sales',
      'totalOrders': 'Total Number of Orders',
      'comparisonByWeekly': 'Comparison by Weekly',
      'previousValue': 'Previous Value',
      'currentValue': 'Current Value',
      'previous': 'Previous',
      'current': 'Current',
      'weekly': 'Weekly',
      'daily': 'Daily',
      'monthly': 'Monthly',
      'shareReport': 'Share Report',
      'printReport': 'Print Report',
      // Wallet
      'wallet': 'Wallet',
      'currentBalance': 'Current Balance',
      'creditLimit': 'Credit Limit',
      'availableCredit': 'Available Credit',
      'topUp': 'Top Up',
      'topUpFor': 'Top Up for',
      'topUpSuccess': 'Top-up successful',
      'transactions': 'Transactions',
      'viewTransactions': 'View Transactions',
      'noTransactions': 'No transactions found',
      'reference': 'Reference',
      'pleaseEnterAmount': 'Please enter amount',
      'invalidAmount': 'Invalid amount',
      // Payment Methods
      'paymentMethods': 'Payment Methods',
      'addPaymentMethod': 'Add Payment Method',
      'editPaymentMethod': 'Edit Payment Method',
      'noPaymentMethods': 'No payment methods found',
      'setAsDefault': 'Set as Default',
      'default': 'Default',
      'type': 'Type',
      'cardNumber': 'Card Number',
      'cardHolderName': 'Card Holder Name',
      'bankName': 'Bank Name',
      'accountNumber': 'Account Number',
      'pleaseEnterName': 'Please enter name',
      'paymentMethodAdded': 'Payment method added',
      'paymentMethodUpdated': 'Payment method updated',
      'deletePaymentMethodConfirmation': 'Are you sure you want to delete this payment method?',
      // Search
      'searchHint': 'Search for products, sales, customers...',
      'noResults': 'No results found',
      // Sales History
      'salesHistory': 'Sales History',
      'ongoing': 'Ongoing',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'noOngoingSales': 'No ongoing sales',
      'noCompletedSales': 'No completed sales',
      'noCancelledSales': 'No cancelled sales',
      'paid': 'Paid',
      'remaining': 'Remaining',
      'reason': 'Reason',
      // Address Book
      'addresses': 'Addresses',
      'addAddress': 'Add Address',
      'noAddresses': 'No addresses found',
      'deleteAddressConfirmation': 'Are you sure you want to delete this address?',
      // Error messages
      'errorPickingImage': 'Error picking image',
      'errorTakingPhoto': 'Error taking photo',
      'errorPickingFile': 'Error picking file',
      'errorSharingReport': 'Error sharing report',
      'errorPrintingReport': 'Error printing report',
      'errorExportingPdf': 'Error exporting PDF',
      'errorExportingExcel': 'Error exporting Excel',
      'errorExportingWord': 'Error exporting Word',
      'error': 'Error',
      // Success messages
      'stockAddedSuccessfully': 'Stock added successfully',
      'pleaseSelectExpiryDate': 'Please select expiry date',
      'reportExportedToPdfSuccessfully': 'Report exported to PDF successfully',
      'reportExportedToWordSuccessfully': 'Report exported to Word successfully',
      'reportExportedToExcelSuccessfully': 'Report exported to Excel successfully',
      'showingLowStockItems': 'Showing low stock items',
      'advancedFilterOptionsComingSoon': 'Advanced filter options coming soon',
      // Dashboard
      'todaySales': 'Today Sales',
      'quickActions': 'Quick Actions',
      'recentActivity': 'Recent Activity',
      'addProduct': 'Add Product',
      'addStaff': 'Add Staff',
      'viewMetrics': 'View Metrics',
      'filters': 'Filters',
      'scheduled': 'Scheduled',
      'script': 'SCRIPT',
      'soh': 'SOH',
      'comparisonBy': 'Comparison by',
      'yearly': 'Yearly',
    };

    // Urdu translations
    _translations['ur'] = {
      'appName': 'فارمیسی POS',
      'appTagline': 'پیشہ ورانہ فارمیسی انتظام',
      'loading': 'لوڈ ہو رہا ہے...',
      'error': 'خرابی',
      'success': 'کامیابی',
      'cancel': 'منسوخ',
      'confirm': 'تصدیق',
      'save': 'محفوظ',
      'delete': 'حذف',
      'edit': 'ترمیم',
      'add': 'شامل',
      'search': 'تلاش',
      'filter': 'فلٹر',
      'clear': 'صاف',
      'retry': 'دوبارہ کوشش',
      'ok': 'ٹھیک',
      'yes': 'ہاں',
      'no': 'نہیں',
      'close': 'بند',
      'login': 'لاگ ان',
      'logout': 'لاگ آؤٹ',
      'email': 'ای میل',
      'password': 'پاس ورڈ',
      'forgotPassword': 'پاس ورڈ بھول گئے؟',
      'register': 'رجسٹر',
      'createAccount': 'اکاؤنٹ بنائیں',
      'dashboard': 'ڈیش بورڈ',
      'sales': 'سیلز',
      'inventory': 'انوینٹری',
      'products': 'مصنوعات',
      'purchases': 'خریدیں',
      'reports': 'رپورٹس',
      'staff': 'عملہ',
      'notifications': 'اطلاعات',
      'settings': 'ترتیبات',
      'subscriptions': 'سبسکرپشن',
      'categories': 'اقسام',
      'inventoryDetails': 'انوینٹری کی تفصیلات',
      'adjustStock': 'اسٹاک ایڈجسٹ کریں',
      'transferStock': 'اسٹاک منتقل کریں',
      'printLabel': 'لیبل پرنٹ کریں',
      'addStock': 'اسٹاک شامل کریں',
      'batch': 'بیچ',
      'quantity': 'مقدار',
      'remainingQuantity': 'بقیہ مقدار',
      'costPrice': 'قیمت لاگت',
      'sellingPrice': 'فروخت کی قیمت',
      'expiryDate': 'ختم ہونے کی تاریخ',
      'expired': 'ختم شدہ',
      'expiringSoon': 'جلد ختم ہونے والا',
      'valid': 'درست',
      'supplier': 'سپلائر',
      'purchaseDate': 'خریداری کی تاریخ',
      'location': 'مقام',
      'additionalInformation': 'اضافی معلومات',
      'lowStock': 'کم اسٹاک',
      'newQuantity': 'نیا مقدار',
      'quantityToTransfer': 'منتقل کرنے کی مقدار',
      'transferTo': 'منتقل کرنا',
      'stockAdjusted': 'اسٹاک کامیابی سے ایڈجسٹ ہو گیا',
      'stockTransferred': 'اسٹاک کامیابی سے منتقل ہو گیا',
      'printingLabel': 'لیبل پرنٹ ہو رہا ہے...',
      'deleteInventory': 'انوینٹری حذف کریں',
      'deleteInventoryConfirmation': 'کیا آپ واقعی اس انوینٹری آئٹم کو حذف کرنا چاہتے ہیں؟',
      'inventoryDeleted': 'انوینٹری حذف ہو گئی',
      'productName': 'پروڈکٹ کا نام',
      'description': 'تفصیل',
      'barcode': 'بارکوڈ',
      'sku': 'SKU',
      'price': 'قیمت',
      'category': 'قسم',
      'addProduct': 'پروڈکٹ شامل کریں',
      'editProduct': 'پروڈکٹ میں ترمیم کریں',
      'updateProduct': 'پروڈکٹ اپ ڈیٹ کریں',
      'productAdded': 'پروڈکٹ شامل ہو گیا',
      'productUpdated': 'پروڈکٹ اپ ڈیٹ ہو گیا',
      'noProducts': 'کوئی پروڈکٹ نہیں ملا',
      'pos': 'POS',
      'cart': 'کارٹ',
      'subtotal': 'ذیلی کل',
      'discount': 'رعایت',
      'tax': 'ٹیکس',
      'total': 'کل',
      'paymentMethod': 'ادائیگی کا طریقہ',
      'processSale': 'سیل پروسیس کریں',
      'cartEmpty': 'کارٹ خالی ہے',
      'filterByCategory': 'قسم کے لحاظ سے فلٹر کریں',
      'allCategories': 'تمام اقسام',
      'searchProducts': 'پروڈکٹس تلاش کریں یا بارکوڈ اسکین کریں',
      'saleSummary': 'سیل کا خلاصہ',
      'invoice': 'انوائس',
      'items': 'اشیاء',
      'printReceipt': 'رسید پرنٹ کریں',
      'downloadReceipt': 'PDF ڈاؤن لوڈ کریں',
      'shareReceipt': 'شیئر کریں',
      'receiptSent': 'رسید پرنٹر کو بھیج دی گئی',
      'receiptDownloaded': 'رسید ڈاؤن لوڈ ہو گئی',
      'receiptReady': 'رسید شیئر کرنے کے لیے تیار',
      'thankYou': 'آپ کی خریداری کا شکریہ!',
      'salesReport': 'سیلز رپورٹ',
      'inventoryReport': 'انوینٹری رپورٹ',
      'generateReport': 'رپورٹ بنائیں',
      'exportToExcel': 'ایکسسل میں برآمد کریں',
      'exportToWord': 'ورڈ میں برآمد کریں',
      'exportToPdf': 'PDF میں برآمد کریں',
      'profile': 'پروفائل',
      'editProfile': 'پروفائل میں ترمیم کریں',
      'darkMode': 'ڈارک موڈ',
      'language': 'زبان',
      'english': 'انگریزی',
      'urdu': 'اردو',
      'theme': 'تھیم',
      'defaultTheme': 'ڈیفالٹ',
      'pharmacyBlue': 'فارمیسی نیلا',
      'medicalGreen': 'میڈیکل سبز',
      'exitMessage': 'خروج کے لیے دوبارہ بیک دبائیں',
      'exitApp': 'ایپ سے باہر نکلیں',
      'exitConfirmation': 'کیا آپ واقعی باہر نکلنا چاہتے ہیں؟',
      'exit': 'خروج',
      'noInventoryItems': 'کوئی انوینٹری آئٹم نہیں ملا',
      'filterInventory': 'انوینٹری فلٹر کریں',
      'clearFilters': 'فلٹرز صاف کریں',
      'scanBarcode': 'بارکوڈ اسکین کریں',
      'selectCustomer': 'کسٹمر منتخب کریں',
      'walkInCustomer': 'واک ان کسٹمر',
      'change': 'تبدیل',
      'addCustomer': 'کسٹمر شامل کریں',
      'added': 'شامل',
      'confirmSale': 'سیل کی تصدیق',
      'customer': 'کسٹمر',
      'amount': 'رقم',
      'addProductsToCart': 'کارٹ میں پروڈکٹس شامل کریں',
      'newPurchase': 'نیا خرید',
      'customers': 'کسٹمرز',
      'searchCustomers': 'کسٹمرز تلاش کریں...',
      'noCustomers': 'کوئی کسٹمر نہیں ملا',
      'addFirstCustomer': 'شروع کرنے کے لیے اپنا پہلا کسٹمر شامل کریں',
      'viewHistory': 'تاریخ دیکھیں',
      'deleteCustomer': 'کسٹمر حذف کریں',
      'deleteCustomerConfirmation': 'کیا آپ واقعی حذف کرنا چاہتے ہیں',
      'customerDeleted': 'کسٹمر حذف ہو گیا',
      'editCustomer': 'کسٹمر میں ترمیم',
      'name': 'نام',
      'phone': 'فون',
      'address': 'پتہ',
      'city': 'شہر',
      'country': 'ملک',
      'dateOfBirth': 'تاریخ پیدائش',
      'gender': 'جنس',
      'customerDetails': 'کسٹمر کی تفصیلات',
      'totalPurchases': 'کل خریداریاں',
      'totalSpent': 'کل خرچ',
      'purchaseHistory': 'خریداری کی تاریخ',
      'noPurchaseHistory': 'کوئی خریداری کی تاریخ نہیں',
      'editPurchase': 'خرید میں ترمیم',
      'supplierName': 'سپلائر کا نام',
      'invoiceNumber': 'انوائس نمبر',
      'purchaseDate': 'خریداری کی تاریخ',
      'addItem': 'آئٹم شامل کریں',
      'editItem': 'آئٹم میں ترمیم',
      'noItemsAdded': 'ابھی تک کوئی آئٹم شامل نہیں',
      'totalAmount': 'کل رقم',
      'attachedFiles': 'منسلک فائلیں',
      'addImage': 'تصویر شامل کریں',
      'addFile': 'فائل شامل کریں',
      'noFilesAttached': 'کوئی فائل منسلک نہیں',
      'createPurchase': 'خرید بنائیں',
      'updatePurchase': 'خرید اپ ڈیٹ کریں',
      'purchaseCreated': 'خرید کامیابی سے بن گئی',
      'addAtLeastOneItem': 'براہ کرم کم از کم ایک آئٹم شامل کریں',
      'product': 'پروڈکٹ',
      'pleaseSelectProduct': 'براہ کرم ایک پروڈکٹ منتخب کریں',
      'batchNumber': 'بیچ نمبر',
      'selectDate': 'تاریخ منتخب کریں',
      // POS Enhanced
      'searchProductsBarcode': 'پروڈکٹس، بارکوڈ، SKU تلاش کریں، یا / کسٹمر کے لیے',
      'advancedFilters': 'اعلی درجے کے فلٹرز',
      'stockOnHand': 'اسٹاک دستیاب',
      'variants': 'متغیرات',
      'selectVariant': 'متغیر منتخب کریں',
      'productType': 'پروڈکٹ کی قسم',
      'otc': 'OTC',
      'rx': 'RX',
      'scriptsWaiting': 'اسکرپٹس انتظار میں',
      'companionProducts': 'ساتھی پروڈکٹس',
      'multiBuy': 'ملٹی خرید',
      // Store/Branch Management
      'selectStore': 'اسٹور منتخب کریں',
      'switchStore': 'اسٹور تبدیل کریں',
      'stores': 'اسٹورز',
      'newStore': 'نیا اسٹور',
      'searchStores': 'اسٹورز تلاش کریں...',
      'noStores': 'کوئی اسٹور نہیں ملا',
      'switchedTo': 'تبدیل ہو گیا',
      'storeTimings': 'اسٹور کے اوقات',
      'addStoreTiming': 'اسٹور کا وقت شامل کریں',
      'serviceType': 'سروس کی قسم',
      'day': 'دن',
      'startTime': 'شروع کا وقت',
      'endTime': 'ختم کا وقت',
      'delivery': 'ڈیلیوری',
      'collection': 'کولیکشن',
      'dineIn': 'ڈائن ان',
      'deliveryRates': 'ڈیلیوری کی شرحیں',
      'addDeliveryRate': 'ڈیلیوری کی شرح شامل کریں',
      'ratePerMileKm': 'فی میل/کلومیٹر شرح',
      'minimumDistance': 'کم سے کم فاصلہ',
      'maximumDistance': 'زیادہ سے زیادہ فاصلہ',
      'deliveryTime': 'ڈیلیوری کا وقت',
      'addOns': 'ایڈ آنز',
      'addOn': 'ایڈ آن',
      'ingredients': 'اجزاء',
      'productSizes': 'پروڈکٹ سائز',
      'isAddonItem': 'کیا یہ ایڈ آن آئٹم ہے؟',
      'allergyNotes': 'الرجی نوٹس',
      'enterAllergyNotes': 'الرجی نوٹس درج کریں...',
      'percentageDiscount': 'فیصد رعایت',
      'addPercentageDiscount': 'فیصد رعایت شامل کریں (اختیاری)',
      'categoryNote': 'قسم کا نوٹ (اختیاری)',
      'enterCategoryNote': 'قسم کا نوٹ یہاں درج کریں...',
      'sorting': 'ترتیب',
      'addSortingId': 'ترتیب ID شامل کریں',
      'shortDescription': 'مختصر تفصیل',
      'isOpenAllDay': 'کیا پورا دن کھلا ہے',
      // Reports Metrics
      'salesAndRevenueMetrics': 'سیلز اور آمدنی کے میٹرکس',
      'trackSalesRevenue': 'تفصیلی بصیرت کے ساتھ سیلز اور آمدنی کے میٹرکس کو ٹریک کریں۔',
      'customerMetrics': 'کسٹمر میٹرکس',
      'analyzeCustomerBehavior': 'کسٹمر کے رویے اور مشغولیت کے نمونوں کا تجزیہ کریں۔',
      'orderMetrics': 'آرڈر میٹرکس',
      'monitorOrderTrends': 'آرڈر کے رجحانات اور عملی کارکردگی کی نگرانی کریں۔',
      'totalSales': 'کل سیلز',
      'totalOrders': 'کل آرڈرز کی تعداد',
      'comparisonByWeekly': 'ہفتہ وار موازنہ',
      'previousValue': 'پچھلی قیمت',
      'currentValue': 'موجودہ قیمت',
      'previous': 'پچھلا',
      'current': 'موجودہ',
      'weekly': 'ہفتہ وار',
      'daily': 'روزانہ',
      'monthly': 'ماہانہ',
      'shareReport': 'رپورٹ شیئر کریں',
      'printReport': 'رپورٹ پرنٹ کریں',
      // Additional missing keys
      'startDate': 'شروع کی تاریخ',
      'endDate': 'ختم کی تاریخ',
      'selectDate': 'تاریخ منتخب کریں',
      'selectExpiryDate': 'ختم ہونے کی تاریخ منتخب کریں',
      'selectCategory': 'ایک قسم منتخب کریں',
      'pleaseSelectCategory': 'براہ کرم ایک قسم منتخب کریں',
      'addNewCategory': 'نیا قسم شامل کریں',
      'updateProduct': 'پروڈکٹ اپ ڈیٹ کریں',
      'addProduct': 'پروڈکٹ شامل کریں',
      'updateStaff': 'عملہ اپ ڈیٹ کریں',
      'addStaff': 'عملہ شامل کریں',
      'updateStock': 'اسٹاک اپ ڈیٹ کریں',
      'addStock': 'اسٹاک شامل کریں',
      'generateReport': 'رپورٹ بنائیں',
      'reportGeneratedSuccessfully': 'رپورٹ کامیابی سے بن گئی',
      'reportExportedToExcelSuccessfully': 'رپورٹ کامیابی سے ایکسل میں برآمد ہو گئی',
      'summary': 'خلاصہ',
      'totalTransactions': 'کل لین دین',
      'averageSale': 'اوسط سیل',
      'topProduct': 'بہترین پروڈکٹ',
      // Image Upload
      'image': 'تصویر',
      'chooseFromGallery': 'گیلری سے منتخب کریں',
      'takePhoto': 'تصویر لیں',
      'tapToAddImage': 'تصویر شامل کرنے کے لیے ٹیپ کریں',
      'active': 'فعال؟',
      'activeCategoryDescription': 'قسم کو "فعال" پر سیٹ کرکے، یہ قسم فہرست میں نظر آئے گی؛ ورنہ یہ چھپی رہے گی۔',
      'submit': 'جمع کریں',
      'addCategory': 'قسم شامل کریں',
      'editCategory': 'قسم میں ترمیم کریں',
      // Wallet
      'wallet': 'والٹ',
      'currentBalance': 'موجودہ بیلنس',
      'creditLimit': 'کریڈٹ کی حد',
      'availableCredit': 'دستیاب کریڈٹ',
      'topUp': 'ٹاپ اپ',
      'topUpFor': 'کے لیے ٹاپ اپ',
      'topUpSuccess': 'ٹاپ اپ کامیاب',
      'transactions': 'لین دین',
      'viewTransactions': 'لین دین دیکھیں',
      'noTransactions': 'کوئی لین دین نہیں ملا',
      'reference': 'حوالہ',
      'pleaseEnterAmount': 'براہ کرم رقم درج کریں',
      'invalidAmount': 'غلط رقم',
      // Payment Methods
      'paymentMethods': 'ادائیگی کے طریقے',
      'addPaymentMethod': 'ادائیگی کا طریقہ شامل کریں',
      'editPaymentMethod': 'ادائیگی کا طریقہ میں ترمیم',
      'noPaymentMethods': 'کوئی ادائیگی کا طریقہ نہیں ملا',
      'setAsDefault': 'ڈیفالٹ کے طور پر سیٹ کریں',
      'default': 'ڈیفالٹ',
      'type': 'قسم',
      'cardNumber': 'کارڈ نمبر',
      'cardHolderName': 'کارڈ ہولڈر کا نام',
      'bankName': 'بینک کا نام',
      'accountNumber': 'اکاؤنٹ نمبر',
      'pleaseEnterName': 'براہ کرم نام درج کریں',
      'paymentMethodAdded': 'ادائیگی کا طریقہ شامل ہو گیا',
      'paymentMethodUpdated': 'ادائیگی کا طریقہ اپ ڈیٹ ہو گیا',
      'deletePaymentMethodConfirmation': 'کیا آپ واقعی اس ادائیگی کے طریقے کو حذف کرنا چاہتے ہیں؟',
      // Search
      'searchHint': 'پروڈکٹس، سیلز، کسٹمرز تلاش کریں...',
      'noResults': 'کوئی نتیجہ نہیں ملا',
      // Sales History
      'salesHistory': 'سیلز کی تاریخ',
      'ongoing': 'جاری',
      'completed': 'مکمل',
      'cancelled': 'منسوخ',
      'noOngoingSales': 'کوئی جاری سیلز نہیں',
      'noCompletedSales': 'کوئی مکمل سیلز نہیں',
      'noCancelledSales': 'کوئی منسوخ سیلز نہیں',
      'paid': 'ادا کیا',
      'remaining': 'بقیہ',
      'reason': 'وجہ',
      // Address Book
      'addresses': 'پتے',
      'addAddress': 'پتہ شامل کریں',
      'noAddresses': 'کوئی پتہ نہیں ملا',
      'deleteAddressConfirmation': 'کیا آپ واقعی اس پتے کو حذف کرنا چاہتے ہیں؟',
      // Error messages
      'errorPickingImage': 'تصویر منتخب کرنے میں خرابی',
      'errorTakingPhoto': 'تصویر لینے میں خرابی',
      'errorPickingFile': 'فائل منتخب کرنے میں خرابی',
      'errorSharingReport': 'رپورٹ شیئر کرنے میں خرابی',
      'errorPrintingReport': 'رپورٹ پرنٹ کرنے میں خرابی',
      'errorExportingPdf': 'PDF برآمد کرنے میں خرابی',
      'errorExportingExcel': 'ایکسسل برآمد کرنے میں خرابی',
      'errorExportingWord': 'ورڈ برآمد کرنے میں خرابی',
      'error': 'خرابی',
      // Success messages
      'stockAddedSuccessfully': 'اسٹاک کامیابی سے شامل ہو گیا',
      'pleaseSelectExpiryDate': 'براہ کرم ختم ہونے کی تاریخ منتخب کریں',
      'reportExportedToPdfSuccessfully': 'رپورٹ کامیابی سے PDF میں برآمد ہو گئی',
      'reportExportedToWordSuccessfully': 'رپورٹ کامیابی سے ورڈ میں برآمد ہو گئی',
      'reportExportedToExcelSuccessfully': 'رپورٹ کامیابی سے ایکسل میں برآمد ہو گئی',
      'showingLowStockItems': 'کم اسٹاک آئٹمز دکھا رہا ہے',
      'advancedFilterOptionsComingSoon': 'اعلی درجے کے فلٹر اختیارات جلد آرہے ہیں',
      // Dashboard
      'todaySales': 'آج کی فروخت',
      'quickActions': 'فوری اعمال',
      'recentActivity': 'حالیہ سرگرمی',
      'addProduct': 'پروڈکٹ شامل کریں',
      'addStaff': 'عملہ شامل کریں',
      'viewMetrics': 'میٹرکس دیکھیں',
      'filters': 'فلٹرز',
      'scheduled': 'شیڈول',
      'script': 'اسکرپٹ',
      'soh': 'SOH',
      'comparisonBy': 'موازنہ',
      'yearly': 'سالانہ',
    };
  }

  String translate(String key) {
    final langCode = locale.languageCode;
    return _translations[langCode]?[key] ?? _translations['en']?[key] ?? key;
  }

  // Getters for common strings
  String get loading => translate('loading');
  String get error => translate('error');
  String get success => translate('success');
  String get cancel => translate('cancel');
  String get confirm => translate('confirm');
  String get save => translate('save');
  String get delete => translate('delete');
  String get edit => translate('edit');
  String get add => translate('add');
  String get search => translate('search');
  String get filter => translate('filter');
  String get clear => translate('clear');
  String get retry => translate('retry');
  String get ok => translate('ok');
  String get yes => translate('yes');
  String get no => translate('no');
  String get close => translate('close');
  String get login => translate('login');
  String get logout => translate('logout');
  String get email => translate('email');
  String get password => translate('password');
  String get dashboard => translate('dashboard');
  String get sales => translate('sales');
  String get inventory => translate('inventory');
  String get products => translate('products');
  String get exitMessage => translate('exitMessage');
  String get exitApp => translate('exitApp');
  String get exitConfirmation => translate('exitConfirmation');
  String get exit => translate('exit');
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ur'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    await AppLocalizations.loadTranslations();
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
